import { expect, test } from "@playwright/test";

test("AI chat sidebar sends a message and updates the board", async ({ page }) => {
  await page.route("**/api/auth/session", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({ user: "user" }),
    });
  });

  await page.route("**/api/kanban", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        id: 1,
        name: "My Board",
        description: null,
        columns: [
          { id: 1, title: "Backlog", position: 0, cards: [] },
          { id: 2, title: "Discovery", position: 1, cards: [] },
          { id: 3, title: "In Progress", position: 2, cards: [] },
          { id: 4, title: "Review", position: 3, cards: [] },
          { id: 5, title: "Done", position: 4, cards: [] },
        ],
      }),
    });
  });

  await page.route("**/api/ai/chat", async (route) => {
    await route.fulfill({
      status: 200,
      contentType: "application/json",
      body: JSON.stringify({
        response: "Created a new card in Backlog.",
        kanban_updates: [
          {
            action: "create_card",
            column_id: 1,
            title: "AI task",
            details: "Generated by AI chat.",
          },
        ],
      }),
    });
  });

  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Kanban Studio" })).toBeVisible();
  await expect(page.locator("[data-testid^=column-]")).toHaveCount(5);

  await page.getByLabel("Chat message").fill("Please add a task to Backlog");
  await page.getByRole("button", { name: /send/i }).click();

  await expect(page.getByText("AI: Created a new card in Backlog.")).toBeVisible();
  await expect(page.getByText("AI task")).toBeVisible();
});
